### ISSUE TITLE
Authors in JSS template for rticles are superimposed, don't know how to put them in two lines

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [rstudio/rticles#100]
I am trying to Write a manuscript for the Journal of Statistical Software (JSS) and I have four authors, the problem is that when I knit the manuscript the affiliation of the authors is superimposed. I have seen that in [Articles with many authors](https://www.jstatsoft.org/article/view/v074i02) in JSS they put them in two lines, but I haven't found any way of doing that int the package Rticles, this is an example manuscript with 4 authors:

    ---
    author:
      - name: Main author
        affiliation: University of life and more
        address: >
           First line
          Second line
         email: me@university.edu
        url: http://rstudio.com
      - name: second author
        affiliation: University of life and more
      - name: Third Author
        affiliation: University of life and more
      - name: Fourth Author
        affiliation: University of life and more
        title:
      formatted: "super interesting r package called \\pkg{TheSuperPackage}"
      short:     "\\pkg{TheSuperPackage}: This is exiting"
    abstract: >
      We present a package that will solve your life
    keywords:
      # at least one keyword must be supplied
      formatted: [ "\\pkg{TheSuperPackage}", Life, "\\proglang{R}"]
      plain:     [keywords, not capitalized, life]
    preamble: >
      \usepackage{amsmath}
    biblio-style: jss
    output:
      rticles::jss_article:
        fig_caption: true
        citation_package: natbib
    bibliography: Derek.bib
    ---

    ```{r, echo=FALSE, warning=FALSE, message=FALSE}
    library(rticles)
    library(rmarkdown)
    library(yaml)
    ```

    ```{r, echo=FALSE, warning=FALSE}
    library(knitr)
    opts_chunk$set(prompt=TRUE)
    options(replace.assign=TRUE, width=90, prompt="R> ")
    ```

    # Introduction

    This template demonstrates some of the basic latex you'll need to know to create a JSS article.

Any help would be greatly appreciated

**Comment by jackwasey** [comment]
This is a horrible work-around. Insert the following into the YAML header:
```
`preamble: '\author{Jack O. Wasey\\Children''s Hospital\\of Philadelphia}'
```
note single quoted to avoid backslash proliferation, and double single ticks. This duplicates the author section of the intermediate tex file, but somehow it seems to work, including not putting newlines in the final authors section with addresses.

**Comment by yihui** [comment]
With the latest development version, I have provided a hack to break the author list into multiple lines. The hack is to add the command `\AND` to the affiliation of the author after which you want to break the line. A minimal example:

```yaml
---
author:
  - name: Main author
    affiliation: 'University of life and more'
    address: >
       First line
       Second line
    email: me@university.edu
    url: http://rstudio.com
  - name: Second author
    affiliation: 'University of life and more \AND'
  - name: Third Author
    affiliation: 'University of life and more'
  - name: Fourth Author
    affiliation: 'University of life and more'
title:
  formatted: "super interesting r package called \\pkg{TheSuperPackage}"
  short:     "\\pkg{TheSuperPackage}: This is exiting"
abstract: >
  We present a package that will solve your life
keywords:
  # at least one keyword must be supplied
  formatted: [ "\\pkg{TheSuperPackage}", Life, "\\proglang{R}"]
  plain:     [keywords, not capitalized, life]
preamble: >
  \usepackage{amsmath}
biblio-style: jss
output:
  rticles::jss_article:
    fig_caption: true
    citation_package: natbib
---
```

````md
# Introduction

Some nice results.

```{r}
1:10
```
````

Please note that you have to use **single quotes** on the affiliation in this case, and there must be **a space** before `\AND`.

Output:

![image](https://user-images.githubusercontent.com/163582/42351114-e5deaa1c-8078-11e8-90de-2aff57bba255.png)
