### ISSUE TITLE
rticles as vignettes

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rticles#154]
Is it possible to use rticles as vignettes in packages? I put a `.Rmd` of a JSS article into the `vignettes` folder, with the following options in the yaml header:

```yaml
output: rticles::jss_article
classoption: nojss
citation_package: natbib
bibliography: jss.bib
vignette: >
  %\VignetteIndexEntry{JSS paper}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
```

etc., but `R CMD build` produces an HTML file instead of a PDF.
