### ISSUE TITLE
Multiple corresponding authors not working for the 'copernicus_article' template

### ISSUE THREAD

**Issue by pzhaonet** [rstudio/rticles#214]
It is a good experience for me to write a Copernicus manuscript with the 'rticles' package. I've just found a problem that it seems not supporting multiple corresponding authors in the 'copernicus_article' template. A mini example could be produced by creating an .Rmd file in RStudio - File - New File - R Markdown - From Template - Copernicus Journal Article, and add one more line to the author information in the yaml:

```
author:
  - given_name: Daniel
    surname: Nüst
    affiliation: 1
    email: daniel.nuest@uni-muenster.de
    corresponding: true
  - given_name: Josiah
    surname: Carberry
    affiliation: 2
    email: j.carberry@orcid.org
    corresponding: true # one more line
  - given_name: Markus
    surname: Konkol
    affiliation: 1
```

Both Daniel and Josiah are supposed to the corresponding authors. However, only the last one is shown in the pdf file.

I found a loop in `library/rticles/rmarkdown/templates/copernicus_article/resources/template.tex`:

```
$for(author)$
$if(author.corresponding)$
\correspondence{$author.given_name$\ $author.surname$\ ($author.email$)}
$endif$
$endfor$
```

I guess there must be something wrong of rmarkdown for processing this loop. I hack the template by setting `correspongdingauthors` in the yaml header and using `$correspongdingauthors$` in the template for temporary use.

Could you please have a look at it if it is a bug? Maybe it is a Pandoc issue? Just not sure...

Thanks a lot!

```
> xfun::session_info('rticles')
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393), RStudio 1.2.1322

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  digest_0.6.18    evaluate_0.13    glue_1.3.1       graphics_3.5.2   grDevices_3.5.2  highr_0.7        htmltools_0.3.6 
  jsonlite_1.6     knitr_1.22       magrittr_1.5     markdown_0.9     methods_3.5.2    mime_0.6         Rcpp_1.0.1       rmarkdown_1.12.2
  rticles_0.7.1    stats_3.5.2      stringi_1.4.3    stringr_1.4.0    tinytex_0.11     tools_3.5.2      utils_3.5.2      xfun_0.5.2      
  yaml_2.2.0
```
