### ISSUE TITLE
Citing in jss() function using LaTex biblatex package -- possible bug

### ISSUE THREAD

**Issue by phargarten2** [rstudio/rticles#219]
By filing an issue to this repo, I promise that

-  [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

Thank you  in creating an Rmarkdown template that allows me to get my article ready for submission to Journal of Statistical Software without leaving Rmarkdown environment. I am having an issue for **knitr** to compile citations using the  **bibLatex** package.[ I already posted it on StackOverflow here](https://stackoverflow.com/questions/55537807/how-to-include-citations-in-the-rticlesjss-function). I first tested using a Mac, and then a Windows. The problem exists on both operating systems. The files used are below. Any help would be appreciated. 

[rticles_jss_issue.zip](https://github.com/rstudio/rticles/files/3069005/rticles_jss_issue.zip)

**Comment by XiangyunHuang** [comment]
@phargarten2 Please do not use biblatex engine. and use **vignette.bib** instead of **vignette_bib.bib**

```
output: 
  rticles::jss_article:
    number_sections: TRUE     #added argument option 
    citation_package: "natbib"  #All my citations use biblatex, not natbib. 
biblio-style: jss      #Listed to use in JSS Instructions for Authors, but not in template by default. 
bibliography: vignette.bib  #Also not included in template by default. 
```
