### ISSUE TITLE
Multi-line affiliations in JSS template

### ISSUE THREAD

**Issue by aldomann** [rstudio/rticles#291]
I am writing the manuscript for the Journal of Statistical Software (JSS) and I switched from doing it in pure LaTeX to the `rticles` package and RMarkdown. 

The issue is most of the affiliations of the authors are quite long, and I want to split the affiliations on the `author` section into two lines (e.g., https://www.jstatsoft.org/article/view/v088i02). I could accomplish this simply by using `\\` manually when defining the affiliations on the `.tex` JSS template, but it doesn't work on the YAML header (nor does `\newline`, as shown in the example).

## Reproducible example

Below a minimal reproducible example of my Rmd document.

```yaml
---
documentclass: jss
author:
  - name: Alfredo Hernández
    affiliation: Universitat Autònoma \newline de Barcelona
    address: >
      Department of Statistics and Mathematics, \newline
      Faculty of Biosciences, \newline
      Universitat Autònoma de Barcelona
    email: \email{aldomann.designs@gmail.com}
    url: \url{aldomann.com}
  - name: David Endesfelder
    affiliation: Bundesamt für Strahlenschutz
  - name: Joan Francesc Barquinero
    affiliation: Universitat Autònoma de Barcelona
title:
  formatted: "\\pkg{Biodose Tools}: An \\proglang{R} \\proglang{Shiny} Application for Biological Dosimetry"
  # If you use tex in the formatted title, also supply version without
  plain:     "Biodose Tools: An R Shiny Application for Biological Dosimetry"
  # For running headers, if needed
  short:     "\\pkg{Biodose Tools}: An \\proglang{R} \\proglang{Shiny} Application for Biological Dosimetry"
abstract: >
  Lorem ipsum.
keywords:
  # at least one keyword must be supplied
  formatted: [keywords, not capitalized, "\\proglang{R}"]
  plain:     [keywords, not capitalized, R]
preamble: >
  \usepackage{amsmath}
output: rticles::jss_article
---

# Introduction

This template demonstrates some of the basic latex you'll need to know to create a JSS article.
```

![image](https://user-images.githubusercontent.com/729732/81916830-41eadf00-95cc-11ea-9ded-319daa2ce2f6.png)

## Solution in LaTeX
As a comparison, this is how I would accomplish it in LaTeX:

```tex
\author{
Alfredo Hernández\\Universitat Autònoma \\ de Barcelona \And David
Endesfelder\\Bundesamt für \\ Strahlenschutz \And Joan Francesc
Barquinero\\Universitat Autònoma \\ de Barcelona
}
```

![image](https://user-images.githubusercontent.com/729732/81916861-516a2800-95cc-11ea-915a-8d300307290c.png)

## Session info

``` r
xfun::session_info("rticles")
#> R version 4.0.0 (2020-04-24)
#> Platform: x86_64-apple-darwin19.4.0 (64-bit)
#> Running under: macOS Catalina 10.15.4
#> 
#> Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8
#> 
#> Package version:
#>   base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.4.0     
#>   graphics_4.0.0  grDevices_4.0.0 highr_0.8       htmltools_0.4.0
#>   jsonlite_1.6.1  knitr_1.28      magrittr_1.5    markdown_1.1   
#>   methods_4.0.0   mime_0.9        Rcpp_1.0.4.6    rlang_0.4.6    
#>   rmarkdown_2.1   rticles_0.14    stats_4.0.0     stringi_1.4.6  
#>   stringr_1.4.0   tinytex_0.22    tools_4.0.0     utils_4.0.0    
#>   xfun_0.13       yaml_2.2.1
```

<sup>Created on 2020-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by aldomann** [comment]
One possible solution would be to force line breaks with `|`, as suggested in #254. For example,
```yaml
  - name: Alfredo Hernández
    affiliation: |
      | Universitat Autònoma 
      | de Barcelona
```

This gives us the expected results:
![image](https://user-images.githubusercontent.com/729732/81921295-49ad8200-95d2-11ea-9155-ca5efcb606eb.png)


However this also affects the Affiliation section at the end of the article (see picture below), which results in a less than ideal formatting.
![image](https://user-images.githubusercontent.com/729732/81921175-1834b680-95d2-11ea-83a5-55829503beee.png)

Would it be possible to keep a long version and a short/multi-line version of the affiliation somehow?
