### ISSUE TITLE
PNAS template ignores "equal_authors" and "corresponding_author"

### ISSUE THREAD

**Issue by EddieItelman** [rstudio/rticles#299]
PNAS template ignores "equal_authors" and "corresponding_author"

To reproduce: Create an rmd document from PNAS template and knit it. You will see that the end product has no corresponding author or equal contribution section.

---

By filing an issue to this repo, I promise that

- [V ] I have fully read the issue guide at https://yihui.name/issue/.
- [V ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [V ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I think there is an issue in the skeleton.Rmd file for this template. 

From `template.tex`, you can only pass value to this field and not a list of values (a Map): 
https://github.com/rstudio/rticles/blob/0567006a2a899a2bb8254522ba78acebe7e259b1/inst/rmarkdown/templates/pnas_article/resources/template.tex#L61-L65

This means in the yaml this should be use:
```yaml
corresponding_author:
  code: 2
  text: "To whom correspondence should be addressed. E-mail: bob@email.com" 
```
and 
```yaml
equal_authors:
  code: 1
  text: "A.O.(Author One) and A.T. (Author Two) contributed equally to this work (remove if not applicable)."
```

Can you try with this syntax ? 

I think it works but I don't know this templates and the requirements. 

If several `code` and `text` can be passed to `equal_authors` or `corresponding_author`, then the template should evolved with some `for` loop in pandoc template. 

@cboettig, as the contributor of this journal template, do you have insights on this ? 
Thank you !
