### ISSUE TITLE
Template crashes when using fig.align or out.width

### ISSUE THREAD

**Issue by EddieItelman** [rstudio/rticles#300]
Sample:
```
---
title: my title
author:
  - name: Edward Itelman
    affiliation: a
  - name: Second Equal
    affiliation: b

address:
  - code: a
    address: Department, Street, City, State, Zip
  - code: b
    address: Department, Street, City, State, Zip

journal: "An awesome journal"
date: "`r Sys.Date()`"


documentclass: article

fontsize: 11pt

geometry: margin=1in
          
header-includes: #allows you to add in your own Latex packages
- \usepackage{float} #use the 'float' package
- \floatplacement{figure}{H} #make every figure with caption = h
- \usepackage{caption}
- \usepackage{chngcntr}
- \usepackage{graphicx}

graphics: yes

output:
  rticles::elsevier_article
---

```{R fig2, echo = F, fig.cap = "Figure1", fig.pos = "h", fig.align = 'center', out.width = '20%'}
plot(mtcars$mpg)```
```

Results in the following error:
```
! Paragraph ended before \Gin@iii was complete.
<to be read again> 
                   \par 
l.153 

Error: LaTeX failed to compile RMD_6.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RMD_6.log for more info.
Execution halted
```

If you remove the fig.align = 'center' and out.width = '20%' - Works like a charm
