### ISSUE TITLE
Add cross-referencing to all rticles

### ISSUE THREAD

**Issue by etiennebr** [rstudio/rticles#328]
I think that it could be easier to use cross-referencing in `rticles`. References to tables, figures and equations are ubiquitous to scientific papers. `bookdown` provides a generic solution that, I think, is more likely to bring users to success from the start. 

``` rmd
\begin{equation}
(\#eq:eq)
c = a \cdot b
\end{equation}
  
see \@ref(eq:eq)
```
Gives 
![image](https://user-images.githubusercontent.com/393576/94365485-6a690680-009f-11eb-83d4-d1d4c7611aa1.png)

[@cderv suggested](https://github.com/rstudio/rticles/pull/327#issuecomment-699619640) that maybe we could provide two possible default outputs in the skeletons. Something like:
``` yaml
output:
  rmarkdown::pdf_document:
    base_format: rticles::mdpi_article
  bookdown::pdf_book: 
    base_format: rticles::mdpi_article
```
It has the benefit that the default output does not require `bookdown`, and it shows that other outputs are possible. While cross-referencing would not work from the start, enabling it would be a matter of picking the next output in the list. If using bookdown as the default output is excluded, then I think this solution is pretty good.

Following #327, I believe that the solution might need to be applied to all skeletons.

**Comment by etiennebr** [comment]
From https://github.com/rstudio/rticles/pull/327#issuecomment-699640117

Make that 
``` yaml
output:
  rticles::mdpi_article: default
  bookdown::pdf_book: 
    base_format: rticles::mdpi_article
```

**Comment by cderv** [comment]
Would a vignette in **rticles** explaining how to use bookdown features by modifying the yaml header be a good idea to better document this ?

**Comment by etiennebr** [comment]
I agree that a vignette would be useful since there are so many options from `bookdown`. I still believe that using `bookdown::pdf_book` as default would enlarge the pit of success, though.

**Comment by sbgraves237** [comment]
I just noticed that figure references stopped working with [Ecfun::ForecastingNuclearProliferation vignette](https://github.com/sbgraves237/Ecfun/blob/master/vignettes/ForecastingNuclearProliferation.Rmd):  For example, the second line of the "Introduction" in the PDF this Rmd file produces used to display "see Figure 1."  Now it displays "see Figure @ref(fig:plot)."  

Section "4.7 Cross-referencing within documents" of "RMarkdown Cookbook" says, ["To use cross-references, you will need: ... an output format from bookdown (e.g., ... pdf_document2 ...) in the YAML output field."](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html).  I changed "output: pdf_document" to "output: pdf_document" and got, "Error in eval(parse(text = name)) : object 'pdf_document2' not found".  

What do you suggest I do to get around this?  Thanks, Spencer Graves

**Comment by etiennebr** [comment]
Hi @sbgraves237, looking at your vignette, this looks like an issue with `bookdown`, rather than `rticles`. But I think the solution is the same than above, although you'll either need `xelatex` or [to include a preamble](https://github.com/rstudio/rticles/issues/325#issue-708207184) with `\DeclareUnicodeCharacter`.

Have you tried
``` yaml
output: 
  bookdown::pdf_book:
    latex_engine: xelatex
```
