### ISSUE TITLE
citecolor and \@ref() in rmarkdown not working accurately

### ISSUE THREAD

**Issue by alexWhitworth** [rstudio/rticles#401]
I'm trying to follow the Bookdown guidance
  - https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html
  - https://bookdown.org/yihui/rmarkdown/pdf-document.html#latex-options

## Problem 1
Use of `\@ref(<label>)` doesn't work. Instead am required to use (`@<label>`) or (`\ref{<label>}`)

## Problem 2
Same issue as in https://github.com/rstudio/rmarkdown/issues/362

## Rmarkdown header

```
---
title: 'rCUPED: user guide'
author: "Alex Whitworth"
date: "May, 2021"
fontsize: 12pt
geometry: margin=0.75in
urlcolor: blue
citecolor: blue
abstract: 'my abstract is super cool'
bibliography: ['bibliography.bib']  
output: 
  pdf_document:
    citation_package: natbib      # exclude when not attempting `\@ref()` labeling
    toc: true
    number_sections: true
    df_print: kable
    fig_width: 6.5
---

my super cool minimally reproducible doc (@devtools)
```

## bibliography

```
@article{devtools,
  title={Package ‘devtools’},
  author={Wickham, Hadley and Hester, Jim and Chang, Winston and Hester, Maintainer Jim},
  year={2020}
}
```

## rticles

```
xfun::session_info('rticles')
R version 4.0.3 (2020-10-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Stream 8, RStudio 1.2.5033

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 digest_0.6.27   evaluate_0.14   glue_1.4.2      graphics_4.0.3  grDevices_4.0.3 highr_0.8      
  htmltools_0.5.0 jsonlite_1.7.2  knitr_1.31      magrittr_2.0.1  markdown_1.1    methods_4.0.3   mime_0.9       
  rlang_0.4.10    rmarkdown_2.6   rticles_0.19    stats_4.0.3     stringi_1.5.3   stringr_1.4.0   tinytex_0.31   
  tools_4.0.3     utils_4.0.3     xfun_0.19       yaml_2.2.1     
```
