### ISSUE TITLE
Do not overwrite any user own existing replication R script for rjournal_article 

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#433]
This was originally posted in https://github.com/rstudio/rticles/issues/394#issuecomment-894316281

We need to watch out to not override any existing R file that would be owned by the user and not generated by us. 

Two ideas: 

* Provide an opt-out mechanism for the purl-ing. 
  Something like 
  ````yaml
  output: 
    rjournal_article: 
      purl: false
  ````

* Use a special comment header `# Do not edit` as done in other tools so that we know that this is our file and we can overwrite.
