### ISSUE TITLE
Modifying elsevier_article() template

### ISSUE THREAD

**Issue by drfurtado** [rstudio/rticles#485]
Hi @cboettig, 

I am seeking to modify the elsevier_article() template.

Issue 1
I need to add information on the top left of the first page similar to [this example](https://www.screencast.com/t/DVVFUeHcGc0x).

Issue 2
When I render the PDF, the words "Preprint submitted" appear on the right [bottom](https://www.screencast.com/t/glgoaFfpU) of the first page. How would I go about omitting those two words?

Any help is greatly appreciated. 
 

---

By filing an issue to this repo, I promise that

- [x ] I have fully read the issue guide at https://yihui.name/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hello @drfurtado 

> Issue 1
> I need to add information on the top left of the first page similar to [this example](https://www.screencast.com/t/DVVFUeHcGc0x).

Is this part of any elsevier tex template ? 

> Issue 2
> When I render the PDF, the words "Preprint submitted" appear on the right [bottom](https://www.screencast.com/t/glgoaFfpU) of the first page. How would I go about omitting those two words?

Do you have `preprint` among the classoption ? This is by default in our skeleton, but I think you would need to remove it. 
https://github.com/rstudio/rticles/blob/dc1733156ba79caf94a8151ee5b8fc0727cb76de/inst/rmarkdown/templates/elsevier/skeleton/skeleton.Rmd#L39

By the way, we are using template for CTAN package elsarticle https://ctan.org/pkg/elsarticle
There is a documentation file to look into also if you need some help configuring

**Comment by drfurtado** [comment]
> Hello @drfurtado
> 
> > Issue 1
> > I need to add information on the top left of the first page similar to [this example](https://www.screencast.com/t/DVVFUeHcGc0x).
> 
> Is this part of any elsevier tex template ?
> 
> > Issue 2
> > When I render the PDF, the words "Preprint submitted" appear on the right [bottom](https://www.screencast.com/t/glgoaFfpU) of the first page. How would I go about omitting those two words?
> 
> Do you have `preprint` among the classoption ? This is by default in our skeleton, but I think you would need to remove it.
> 
> https://github.com/rstudio/rticles/blob/dc1733156ba79caf94a8151ee5b8fc0727cb76de/inst/rmarkdown/templates/elsevier/skeleton/skeleton.Rmd#L39
> 
> By the way, we are using template for CTAN package elsarticle https://ctan.org/pkg/elsarticle There is a documentation file to look into also if you need some help configuring

I did delete `preprint` but the word still appears on the rendered pdf. I even tried to add `final` but to no avail. I did look at the documentation file but could find a solution for this problem. 

Below is the FM file I am using:

```
---
title: Short Paper
author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliation: Some Institute of Technology
    correspondingauthor: true
    footnote: 1
  - name: Bob Security
    email: bob@example.com
    affiliation: Another University
  - name: Cat Memes
    email: cat@example.com
    affiliation: Another University
    footnote: 2
  - name: Derek Zoolander
    email: derek@example.com
    affiliation: Some Institute of Technology
    footnote: 2
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
footnote:
  - code: 1
    text: "This is the first author footnote."
  - code: 2
    text: "Another author footnote."
abstract: |
  This is the abstract. sx sd s d sds ds d s dsd sdsdsdsdsdsd sd s d sd s ds d sd s d sd s d sd s d sd s d sd s d sd   s ds dsdsdsdsdsdsdsdsds d sd sd sdsdsdsds d sdsd sd s d sd  sd sd  sd s d sd s d sds ds d s dsdsdsdsdsd  sdsdsdsdsdsdsdsdsdsdsd sd sd s dnskdnskdn sk d sdn sd sd  ns d sd snd ks dkns d.

keywords: 
  - keyword1
  - keyword2
journal: "Journal of Kinesiology and Wellness"
date: "`r Sys.Date()`"
classoption: 5p, authoryear
bibliography: mybibfile.bib
linenumbers: false
numbersections: false
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
---
```
