### ISSUE TITLE
ieee multiple affiliations

### ISSUE THREAD

**Issue by phamdn** [rstudio/rticles#500]
It seems that the current ieee Rmd template does not support multiple affiliations per author. I tried `mark: 1,2` but not working. Thanks.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by temospena** [comment]
I am also facing the same issue with multiple authors, but in elsevier.
Tried

```
author:
  - name: Abcd Efgh\corref{cor1} #otherwise asterisk does not show
    affiliation: 1
    correspondingauthor: true
    email: mail@bla.pt
  - name: Ghij Klm
    affiliation: 1
    affiliation2: 2
address:
  - code: 1
    address: "abdcgjkf Lisboa, Portugal"
  - code: 2
    address: "owjfnruj Lisboa, Portugal"
```

and also

```
author:
  - name: Abcd Efgh\corref{cor1} #otherwise asterisk does not show
    affiliation: 1
    correspondingauthor: true
    email: mail@bla.pt
  - name: Ghij Klm
    affiliation: 1, 2
address:
  - code: 1
    address: "abdcgjkf Lisboa, Portugal"
  - code: 2
    address: "owjfnruj Lisboa, Portugal"
```

And both give a result of:
Abcd Efgh<sup>*,a</sup>, Ghij Klm<sup>a,1</sup>

instead of <sup>a,b</sup>

**Comment by temospena** [comment]
I am sorry, just found a solution for my problem in #91 
There was a extra space after the comma, in the second option.

**Comment by cderv** [comment]
I am not expert on IEEE but https://github.com/rstudio/rticles/pull/184 and  https://github.com/rstudio/rticles/pull/263 introduced some flexibility. I don't know which you expect but it seems that it is possible 
From commit  54394deaaa3961e41a7a4a483a41aabb8e57dfd5 description
> * added support for new authors layouts.
> There are now 3 possible styles:
> 	- author-columnar, the one in the original template according to IEEETran for max 3 authors
>	- institution-columnar, where authors are grouped per instituion
> 	- wide, as described in IEEETrans template

The second one seems the one to use when multiple author per affiliation. This is the default in our skeleton template. You can add any author to institution like this 
````yaml
    - name: Starfleet Academy
      location: San Francisco, California 96678-2391
      other: "Telephone: (800) 555--1212, Fax: (888) 555--1212"
      mark: 3
      author:
        - name: Montgomery Scott
        - name: Eldon Tyrell
          email: eldon@starfleet-academy.star
    - name: Tyrell Inc.
      location: 123 Replicant Street, Los Angeles, USA 90210--4321
      mark: 4
      author:
        - name: Eldon Tyrell
          email: eldon@starfleet-academy.star
        - name: Roy Batty
          email: roy@replicant.offworld
````
![image](https://user-images.githubusercontent.com/6791940/229140122-345ddc39-5e18-4aad-9cec-2467c43fab0f.png)

To do it using the `mark`, it probably requires a tweak in the template. Do you know how you would do that in LaTeX directly ?

**Comment by cderv** [comment]
#525 adds supports for this syntax
````yaml
  author:   
   - name: Eldon Tyrell
     mark: [2, 3]
     email: eldon@starfleet-academy.star
````

which should allow several affiliation when using `wide: true` mode for authors
