### ISSUE TITLE
Affiliation rendering incorrectly with elsev article 

### ISSUE THREAD

**Issue by gjpstrain** [rstudio/rticles#509]
The elsevier article class does not render commas between different parts of the address for the affiliations. Other punctuation renders correctly (period etc.), but the commas between e.g Department, State etc do not render. This happens when knitting the elsevier article straight out of the box, and I have replicated this with Rstudio cloud as well.

The intermediate .tex file has the commas in it, but for some reason they do not render.  Below is what the .tex looks like, which doesn't work. 

```
  \fnref{2}}
   \ead{derek@example.com} 
      \affiliation[Some Institute of Technology]{Department, Street,
City, State, Zip}
```
Below is a change that does work, but unfortunately I don't know how to reverse-engineer this so the rmarkdown produces it in the .tex file.

```
  \fnref{2}}
   \ead{derek@example.com} 
      \affiliation[Some Institute of Technology]{
		organization = {Department},
		addressline = {A street 29},
		postcode = {2054 NX},
		city = {Manchester},
		country = {The Netherlands}}
```
I have asked this on stackoverflow - https://stackoverflow.com/questions/74197086/elsevier-rticle-not-rendering-affiliation-properly
---

By filing an issue to this repo, I promise that

- [ x] I have fully read the issue guide at https://yihui.name/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks for the report

You can now do the affiliation like 

```yaml
address:
  - code: Some Institute of Technology
    organization: Big Wig University
    addressline: 1 main street
    city: Gotham
    state: State
    postcode: 123456
    country: United States
  - code: Another University
    organization: Department
    addressline: A street 29
    postcode: 2054 NX
    city: Manchester,
    country: The Netherlands
````

It should solve the issue. `address` should still be supported and not break your current workaround
