### ISSUE TITLE
Multiple affiliations in Elsevier yaml header 

### ISSUE THREAD

**Issue by hmep** [rstudio/rticles#511]
I am having trouble finding a way to specify multiple affiliations in the yaml header for the Elsevier template. I have tried generalizing the way multiple entries are specified elsewhere, using indentation and hyphens, like so

    - name: NN
    affiliation:
        - a university 
        - and another
  
to no avail. I also tried multiple affiliation entries, like so

    - name: NN
    affiliation: a university 
    affiliation: and another

as well as variations of the following

    - name: NN
    affiliation: ‘a university, and another’

neither of which worked. Is there a way to accomplish this?

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by temospena** [comment]
Try

```
author:
  - name: NN
    affiliation: university1,university2 
    #no space between comma
address:
  - code: university1
    address: a university somewhere
  - code: university2
    address: a university elsewhere
```
