### ISSUE TITLE
Biobliography not formatted correctly in rticles::elsevier_article

### ISSUE THREAD

**Issue by pepijn-devries** [rstudio/rticles#545]
Thanks for your work on rticles. It really helped me to streamline my publication process.

When using `rticles::elsevier_article` I noticed that the bibliography was formatted incorrectly (e.g., first names showing first instead of last names). For me adding `biblio-style: elsarticle-harv` to the yaml header fixed the issue. Maybe this can be included in the default template, or it can be noted in the documentation?

This is my session info:

``` r
sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
#> [3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
#> [5] LC_TIME=Dutch_Netherlands.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.31   withr_2.5.0     lifecycle_1.0.3 reprex_2.0.2   
#>  [5] evaluate_0.21   rlang_1.1.0     cli_3.4.1       rstudioapi_0.13
#>  [9] fs_1.6.2        rmarkdown_2.22  tools_4.1.1     glue_1.6.2     
#> [13] xfun_0.37       yaml_2.3.7      fastmap_1.1.0   compiler_4.1.1 
#> [17] htmltools_0.5.4 knitr_1.42
```

<sup>Created on 2023-10-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

@cboettig @robjhyndman

**Comment by cderv** [comment]
It seems the template was done using `plainnat` by default
https://github.com/rstudio/rticles/blob/fcbcf83c739b98971e3122a179a5448f993e73d2/inst/rmarkdown/templates/elsevier/resources/template.tex#L57-L60

The LaTeX package guideline (https://www.elsevier.com/authors/policies-and-guidelines/documents/elsdoc-1.pdf)
> Three bibliographic style files (*.bst) are provided — elsarticle-num.bst,
elsarticle-num-names.bst and elsarticle-harv.bst

I am fine by using one of this as the default if that is better

**Comment by pepijn-devries** [comment]
Or perhaps include all options in the template and comment out all but one. Than it is visible to the user what the options are.

**Comment by cderv** [comment]
In fact re-reading the guidelines, I am seeing this about class option
> `authoryear`
> author-year citation style of natbib.sty. If you want to add
extra options of natbib.sty, you may use the options as comma
delimited strings as arguments to \biboptions command. 

And we use it in the template in `classoptions`. Is it set for you ?

**Comment by pepijn-devries** [comment]
This is what my yaml-header looks like at the moment. I do have the `authoryear` option set at the `classoptions`. But without the `biblio-style` setting defined the bibliography is not formatted correctly. I've added it myself to the default template.

```yaml
title: "TODO"
author:
  - name: TODO
    email: TODO
    affiliation: TODO
    correspondingauthor: true
address:
  - code: WUR
    organization: TODO
    addressline: TODO
    city: TODO
    postcode: TODO
    country: The Netherlands
abstract: |
  TODO
keywords: 
  - TODO
  - TODO
journal: "TODO"
date: "`r Sys.Date()`"
classoption: preprint, 3p, authoryear
bibliography: library.bib
biblio-style: elsarticle-harv
linenumbers: true
numbersections: true
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
```
