### ISSUE TITLE
AEA article bibliography does not work

### ISSUE THREAD

**Issue by lyuben-ivanov** [rstudio/rticles#584]
I tried to compile a new AEA article and it works as expected but ONLY if I don't use any bibtex citations. 

After I add  

```
bibliography: orange-economy-bibliography.bib
```

to the YAML header I get an error that I can not fix:  

_! Package natbib Error: Bibliography not compatible with author-year citations._

The .bib file itself is properly formatted and works flawlessly with 'knitr' when the following YAML settings are specified:

```
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: true 
bibliography: orange-economy-bibliography.bib
csl: harvard-cite-them-right.csl
```
