### ISSUE TITLE
References on jss template show a ? Sign

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [rstudio/rticles#63]
Hello:

I have problems adding References to the jss template. I have use the elsevier template with no problem. I also tried changin the @reference to \cite{references} or \citep{references} but a ? Sign appears where the references should be. I feel I am not pointing to the .bib file in the right way. Any idea of what I am doing wrong?

**Comment by yihui** [comment]
How about this?

```yaml
output:
  rticles::jss_article:
    citation_package: natbib
bibliography: your-references.bib
```
