### ISSUE TITLE
Author addresses in Elsevier

### ISSUE THREAD

**Issue by frenchja** [rstudio/rticles#64]
The [Elsevier skeleton](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/elsevier_article/skeleton/skeleton.Rmd) should probably be updated to include the proper YAML for setting different addresses:

```
address:
  - code: University 1
    address: Department, Street, City, State, Zip
  - code: University 2
    address: Department, Street, City, State, Zip
```

This isn't clear from the RMarkdown provided skeleton unless one digs into the accompanying [skeleton.tex](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/elsevier_article/resources/template.tex#L172-L174) for the document class.
