### ISSUE TITLE
elsevier: multiple affiliations per author & set journal name

### ISSUE THREAD

**Issue by januz** [rstudio/rticles#91]
I'm having the following problems using the elsevier template:

1) I'd like to set multiple affiliations per author. There seems to be a workaround (https://stackoverflow.com/questions/29554211/customising-r-markdown-pdf-document), but then the superscript is also present in the author name that is given in parentheses behind the e-mail address)

2) I'd like to set the journal name to be printed in the "preprint submitted to ..." line

Are those things possible?

**Comment by cboettig** [comment]
Hi @januz 

1) Note that affiliation is just a code, and multiple codes can be listed for any author, e.g.

```yaml

author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliation: a,b
    footnote: Corresponding Author
  - name: Bob Security
    email: bob@example.com
    affiliation: b
address:
  - code: a
    address: Department, Street, City, State, Zip
  - code: b
    address: Department, Street, City, State, Zip

```

Will give Alice two affiliations.  

2) Regarding "Preprint submitted to Elsevier", that is an often-requested feature.  Unfortunately, that setting is hard-coded in the `elsarticle.cls` file which does not expose any option to customizing that value (see the [elsarticle manual](https://www.elsevier.com/__data/assets/pdf_file/0008/56843/elsdoc-1.pdf)).  Note that Elsevier owns the copyright to `elsarticle.cls` and permits redistribution only in unmodified form under the terms of the [LaTeX Public License](http://www.latex-project.org/lppl.txt), as stated in the `.cls` file header, so we cannot simply hack the class file to make that possible.  

(Perhaps that permits you to modify the `.cls` file yourself for your own use, as long as you are not distributing it; but IANAL and this isn't legal advice ;-) )
